server:
  port: 8080

spring:
  application:
    name: campus-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jsz20011006

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.twilight.campus.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


